// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4Niipz3S38KGddwhXp_eZq_lO44eAv8',
    appId: '1:142401307068:web:bc5fd7a4d6d92c955fabb9',
    messagingSenderId: '142401307068',
    projectId: 'test2-76c77',
    authDomain: 'test2-76c77.firebaseapp.com',
    storageBucket: 'test2-76c77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAl92lbjBOF-toMf5oGxb1E_pPue29vco',
    appId: '1:142401307068:android:5be78c76a1fbc1265fabb9',
    messagingSenderId: '142401307068',
    projectId: 'test2-76c77',
    storageBucket: 'test2-76c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Zjk8bAgIgi4GJGotwtgKYBZ8yU5-S4k',
    appId: '1:142401307068:ios:bf73f0d7274891715fabb9',
    messagingSenderId: '142401307068',
    projectId: 'test2-76c77',
    storageBucket: 'test2-76c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Zjk8bAgIgi4GJGotwtgKYBZ8yU5-S4k',
    appId: '1:142401307068:ios:bf73f0d7274891715fabb9',
    messagingSenderId: '142401307068',
    projectId: 'test2-76c77',
    storageBucket: 'test2-76c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY4Niipz3S38KGddwhXp_eZq_lO44eAv8',
    appId: '1:142401307068:web:b8fc7eed9101111d5fabb9',
    messagingSenderId: '142401307068',
    projectId: 'test2-76c77',
    authDomain: 'test2-76c77.firebaseapp.com',
    storageBucket: 'test2-76c77.firebasestorage.app',
  );
}
